package com.vlad.fargutu.exchange.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COURSE_VALUE.
 */
public class CourseValue {

    private long id;
    private Float purchase;
    private Float sale;
    private java.util.Date updatedDate;
    private Long courseId;
    private Long bankId;

    public CourseValue() {
    }

    public CourseValue(long id) {
        this.id = id;
    }

    public CourseValue(long id, Float purchase, Float sale, java.util.Date updatedDate, Long courseId, Long bankId) {
        this.id = id;
        this.purchase = purchase;
        this.sale = sale;
        this.updatedDate = updatedDate;
        this.courseId = courseId;
        this.bankId = bankId;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Float getPurchase() {
        return purchase;
    }

    public void setPurchase(Float purchase) {
        this.purchase = purchase;
    }

    public Float getSale() {
        return sale;
    }

    public void setSale(Float sale) {
        this.sale = sale;
    }

    public java.util.Date getUpdatedDate() {
        return updatedDate;
    }

    public void setUpdatedDate(java.util.Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Long getCourseId() {
        return courseId;
    }

    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    public Long getBankId() {
        return bankId;
    }

    public void setBankId(Long bankId) {
        this.bankId = bankId;
    }

}
