package com.exchange.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COURSE_VALUE.
 */
public class CourseValue {

    private long id;
    private Float purchase;
    private Float sale;
    private java.util.Date updatedDate;
    private String courseCode;
    private String bankName;

    public CourseValue() {
    }

    public CourseValue(long id) {
        this.id = id;
    }

    public CourseValue(long id, Float purchase, Float sale, java.util.Date updatedDate, String courseCode, String bankName) {
        this.id = id;
        this.purchase = purchase;
        this.sale = sale;
        this.updatedDate = updatedDate;
        this.courseCode = courseCode;
        this.bankName = bankName;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Float getPurchase() {
        return purchase;
    }

    public void setPurchase(Float purchase) {
        this.purchase = purchase;
    }

    public Float getSale() {
        return sale;
    }

    public void setSale(Float sale) {
        this.sale = sale;
    }

    public java.util.Date getUpdatedDate() {
        return updatedDate;
    }

    public void setUpdatedDate(java.util.Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public String getCourseCode() {
        return courseCode;
    }

    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode;
    }

    public String getBankName() {
        return bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

}
